# Generated by Django 5.1.2 on 2024-11-27 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExamInfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='Type',
            field=models.CharField(default='coding', max_length=100, unique=True),
        ),
    ]
