# Generated by Django 5.1.2 on 2024-11-27 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExamInfo', '0002_exam_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='Type',
            field=models.CharField(default='coding', max_length=100),
        ),
    ]
