# Generated by Django 5.1.2 on 2024-11-26 13:32

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(choices=[('design', 'Design'), ('coding', 'Coding'), ('marketing', 'Marketing')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DomainSpecificAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=20, null=True)),
                ('design_file_url', models.URLField(blank=True, null=True)),
                ('design_description', models.TextField(blank=True, null=True)),
                ('video_file_url', models.URLField(blank=True, null=True)),
                ('video_description', models.TextField(blank=True, null=True)),
                ('question_id', models.CharField(max_length=50)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain_specific_answer', to='submission.examsubmission')),
            ],
        ),
        migrations.CreateModel(
            name='DescriptiveAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.CharField(max_length=50)),
                ('answer', models.TextField()),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptive_answers', to='submission.examsubmission')),
            ],
        ),
        migrations.CreateModel(
            name='BehaviorAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_likely_bot', models.BooleanField(default=False)),
                ('confidence', models.FloatField()),
                ('reasons', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, size=None)),
                ('key_timing', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None)),
                ('special_key_count', models.IntegerField()),
                ('typing_speed', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=list, size=None)),
                ('backspace_count', models.IntegerField()),
                ('total_key_presses', models.IntegerField()),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_analysis', to='submission.examsubmission')),
            ],
        ),
        migrations.CreateModel(
            name='MCQAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.CharField(max_length=50)),
                ('answer', models.CharField(max_length=255)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcq_answers', to='submission.examsubmission')),
            ],
        ),
    ]
