# Generated by Django 5.1.2 on 2024-11-27 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='descriptiveanswer',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='examsubmission',
            name='total_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mcqanswer',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
