# Generated by Django 5.1.2 on 2024-11-27 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0002_descriptiveanswer_score_examsubmission_total_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='domainspecificanswer',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='descriptiveanswer',
            name='score',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='examsubmission',
            name='total_score',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='mcqanswer',
            name='is_correct',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
