# Generated by Django 5.1.2 on 2024-11-27 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0003_domainspecificanswer_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlagarismAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('confidence', models.FloatField()),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Plagarism_Analysis', to='submission.examsubmission')),
            ],
        ),
    ]
